export type Role = 'owner' | 'manager' | 'sales';

export type PermissionAction =
  | 'product:view'
  | 'product:create'
  | 'product:edit'
  | 'product:delete'
  | 'product:detail'
  | 'category:create'
  | 'movement:view'
  | 'movement:create'
  | 'movement:entry'
  | 'movement:withdrawal'
  | 'movement:view_costs'
  | 'movement:details'
  | 'movement:cancel_sale'
  | 'stock:view_costs'
  | 'team:manage'
  | 'customer:view'
  | 'customer:manage'
  | 'order:view_all'
  | 'order:view_own'
  | 'order:create'
  | 'order:manage'
  | 'catalog:view'
  | 'catalog:manage'
  | 'storefront:manage'
  | 'financial:view'
  | 'org:create'
  | 'org:update'
  | 'org:manage';
