export type { IProduct, VariantOption } from './domain/entities';
export { getGradeStockConsolidation } from './domain/utils/get-grade-stock-consolidation';
export { VariantOptionBadge } from './presentation/components/variants-options-badge';
export { useProductsQuery } from './presentation/hooks/use-queries';
export { CreateProductPage } from './presentation/pages/create-product';
export { EditProductPage } from './presentation/pages/edit-product';
export { ImportProductsPage } from './presentation/pages/import-products';
export { ProductDetailsPage } from './presentation/pages/product-detail';
export { ProductsListPage } from './presentation/pages/product-list';
export { formatVariantOptions } from './presentation/utils/format-variant-options';
